project:
  type: website
  output-dir: docs

website:
  title: "Tandy Center for Ocean Forecasting"
  site-url: https://bigelowlab.github.io/tandy-blog/
  description: "Data science blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bigelowlab/tandy-blog
      - icon: rss
        href: sitemap.xml
html:
  theme: cosmo
  css: styles.css
