project:
  type: website

website:
  title: "Tandy Center for Ocean Forecasting"
  description: "Data science blog for the Tandy Center"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bigelowlab/tandy-blog
html:
  theme: cosmo
  css: styles.css
